project = "flypose"
path = "/media/beast/pierre/flywalk-pipeline-go/test2"
model_folder = "/home/tuthill/pierre/flypose-test-Pierre-2018-12-10"

nesting = 1

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid
board_size = [6, 6]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 4

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 50

# length of marker side
board_marker_length = 0.375  # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 0.5  # mm

animal_calibration = False

[filter]
enabled = true
medfilt = 13
offset_threshold = 25
score_threshold = 0.8
spline = true

[labeling]
scheme = [
    ["L1A", "L1B", "L1C", "L1D", "L1E"],
    ["L2A", "L2B", "L2C", "L2D", "L2E"],
    ["L3A", "L3B", "L3C", "L3D", "L3E"],
]

[triangulation]
cam_regex = "_([A-Z])$"
axes = [["x", "L1A", "L3A"], ["z", "L1B", "L1A"]]
reference_point = "L1A"
cam_align = "C"

[angles]
L1_CF = ["L1A", "L1B", "L1C"]
L1_FTi = ["L1B", "L1C", "L1D"]
L1_TiTa = ["L1C", "L1D", "L1E"]

L2_CF = ["L2A", "L2B", "L2C"]
L2_FTi = ["L2B", "L2C", "L2D"]
L2_TiTa = ["L2C", "L2D", "L2E"]

L3_CF = ["L3A", "L3B", "L3C"]
L3_FTi = ["L3B", "L3C", "L3D"]
L3_TiTa = ["L3C", "L3D", "L3E"]


[cameras.A]
offset = [224, 120, 832, 704]

[cameras.B]
offset = [224, 230, 800, 700]

[cameras.C]
offset = [160, 250, 864, 700]
